# Generated by Django 5.1.3 on 2024-12-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matric_number", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("gender", models.CharField(max_length=1)),
                ("field_of_study", models.CharField(max_length=50)),
                ("ca_score", models.FloatField()),
                ("exam_score", models.FloatField()),
            ],
        ),
    ]
