# Generated by Django 5.1.3 on 2024-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="ca_score",
            new_name="CA_Score",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="email",
            new_name="Email",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="exam_score",
            new_name="Exam_Score",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="field_of_study",
            new_name="Field_of_Study",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="first_name",
            new_name="First_Name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="last_name",
            new_name="Last_Name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="matric_number",
            new_name="Matric_Number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
        migrations.AddField(
            model_name="student",
            name="Gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
        ),
    ]
