# Generated by Django 5.1.3 on 2024-12-03 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_rename_ca_score_student_ca_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="CA_Score",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(30)]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="Exam_Score",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(70)]
            ),
        ),
    ]
