# Generated by Django 5.1.3 on 2024-12-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_ca_score_alter_student_exam_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="Gender",
        ),
    ]
